version: "3.3"

services:
  app:
    image: rossedlin/minecraft:1.13.2
    ports:
      - "25565:25565"
      - "8123:8123"
    stdin_open: true
    tty: true
    env_file:
      - .env
#    volumes:
#      - ./tmp:/tmp
